language: python
python:
  - "3.4"
  - "3.5"

sudo: required

# install dependencies
before_install:
  - pip install networkx

# install pylangacq
install:
  - python setup.py install

# run tests
#script:
#  - bash pytest_run.sh
